{% set name = "ripgrepy" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ripgrepy-{{ version }}.tar.gz
  sha256: 86b8ed6cf99da0bddab3281290078a3c3704c670c109afb37fd884485cf4a720

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ripgrep >=11.0.1,<12

test:
  imports:
    - ripgrepy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/securisec/ripgrepy
  summary: python module for ripgrep
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
